package com.example.nutrifit.products

object ConsejosDataSource {
    val consejos = listOf(
        "Tomá 2 litros de agua por día 💧",
        "Dormí al menos 7 horas 😴",
        "Comé frutas y verduras todos los días 🍎🥦",
        "Reducí el consumo de azúcar 🧁",
        "Hacé ejercicio regularmente 🏃‍♂️",
        "Tomate descansos durante el estudio o trabajo 🧘",
        "No te saltees el desayuno 🍳",
        "Evitá el consumo excesivo de alcohol 🍻",
        "Mantené una buena postura 🧍",
        "Reíte más, el humor también es salud 😄",
        "Laváte las manos con frecuencia 🧼",
        "Salí a caminar al aire libre 🌳",
        "Cuidá tu salud mental, hablá con alguien ❤️",
        "Consumí omega 3: pescados, semillas y nueces 🐟🥜",
        "Limitá el consumo de comida ultraprocesada 🍔",
        "Organizá tus comidas, evitá el picoteo sin hambre 🕒",
        "Chequeá tu presión regularmente 🩺",
        "No fumes 🚭",
        "Evitá pantallas al menos 30 minutos antes de dormir 📵",
        "Practica respiración consciente 5 minutos por día 🌬️",
        "Cuidá tu piel, usá protector solar 🌞",
        "No tomes medicamentos sin receta médica 💊",
        "Aprendé algo nuevo, entrená tu cerebro 🧠",
        "Consumí alimentos ricos en fibra 🥖🍌",
        "Mantené tus controles médicos al día 📋",
        "Disfrutá tus comidas, comé sin distracciones 🍽️",
        "Evitá el estrés innecesario, priorizá tu bienestar 💆",
        "Caminá al menos 30 minutos al día 🚶‍♂️",
        "Consumí legumbres 2 o 3 veces por semana 🫘",
        "Limpiá tu entorno, orden externo es paz mental 🧹",
        "Escuchá música que te relaje 🎵",
        "Ponete objetivos realistas y celebrá tus avances 🏅",
        "Desayuná con proteínas: huevo, yogur, frutos secos 🍳🥛",
        "No te olvides de hidratarte aunque no tengas sed 💦",
        "Consumí menos sal para cuidar tu corazón ❤️",
        "Leé libros que te inspiren 📚",
        "Tomá té de hierbas naturales en lugar de gaseosas 🍵",
        "Elegí escaleras en vez del ascensor cuando puedas 🧗",
        "Cuidá tus ojos: pausas cada 20 min si usás pantalla 👀",
        "Disfrutá una fruta de estación todos los días 🍓🍊",
        "Agradecé algo todos los días, lo que sea 🙏",
        "Bailá aunque no sepas, libera endorfinas 💃",
        "Tené una rutina de sueño regular 🛌",
        "Reducí el tiempo en redes sociales 📱",
        "Cociná en casa más seguido, elegí los ingredientes 👩‍🍳",
        "Planificá tu semana, ganás tiempo y orden 🗓️",
        "Evitá compararte con otros, tu progreso es único ✨",
        "Pasá tiempo con quienes te hacen bien 🤗",
        "Cuidá tus dientes, cepillalos mínimo 2 veces al día 🪥"
    )

    fun random(): String = consejos.random()
}